### ISSUE TITLE
要不要搞一个评论系统

### ISSUE THREAD

**Issue by ghost** [cshsonice/site#1]

**Comment by chxv** [comment]
好像也没人会来评论吧qaq

**Comment by chxv** [comment]
done

**Comment by ghost** [comment]
Q_Q
是不是之前 曾几何时 开启过 评论功能...

**Comment by chxv** [comment]
之前用的是海外的 vps 搭的评论系统，太贵了就停了，国内有 vps 但是要备案
我抽空再看看吧，开源评论系统一般都带 html 接口，容易被封，只有纯 api 接口才能用

**Comment by chxv** [comment]
@PandaTea 可
